[package]
name = "sdl-frontend"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chip = { path = "../chip" }
clap = { version = "4.5.1", features = ["derive"] }
sdl2 = "0.36.0"
